name: Pre-commit

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: mastodata/.github/.github/workflows/pre-commit.yaml@main
