name: Test

on:
  workflow_run:
    workflows: ["Pre-commit"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # 3.6.0

      - name: Setup PDM
        uses: pdm-project/setup-pdm@ddc33ca746b5716353581f988b29464200212702  # 3.3.0
        with:
          python-version: "3.11"
          cache: true

      - name: Install dependencies
        run: pdm install --dev

      - name: Run tests
        run: pdm test

  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-22.04
    steps:
      - run: echo 'Pre-commit failed'
